pkg/client/client.go
This PR adds performance debug logs on the client side to avoid having performance measuring code on the application layer.
=> Client side performance logs

cmd/immu/immu.go
=> chore: rename command "verify" to "check-consistency"

.gitignore, cmd/cmd.go, cmd/immu/immu.go, cmd/immud/immud.go, cmd/immugw/immugw.go, pkg/gw/options.go, pkg/server/server.go
as requested by Andrei in this comment: https://github.com/codenotary/immudb/issues/63#issuecomment-612115102
=> Chore: do not persist auth keys

Makefile
=> chore: remove immuclient from default make target

Makefile
=> chore: instructions after make

pkg/server/server.go, pkg/store/store.go
=> chore: info if starting server with empty database

CONTRIBUTING.md
Hi, just a trivial fix (netdata -> immudb).
=> Fix project name in CONTRIBUTING.md

Dockerfile.immuadmin, Dockerfile.immugw, README.md
update README and Dockerfiles to reflect new env variables
=> reflect new env vars - Readme and Dockerfile

README.md
Hello, I saw you post your project on Reddit.
While taking a read of your README, I noticed some grammatical mistakes and have raised this PR to address them.
Seems like an interesting project and I wish you all the best!
=> Correcting grammar in README.md

README.md
Fix readme instruction to start immugw
=> fix: readme doc, immugw start command

pkg/gw/types.go, pkg/server/types.go
=> chore: rename default immudb and immugw loggers

cmd/immuadmin/command/login.go
=> chore(immuadmin): improve the very first login message

README.md, cmd/immuadmin/command/backup.go
=> fix: disallow running immuadmin backup with current directory as source

cmd/immuclient/cli/misc.go, cmd/immuclient/cli/register.go, cmd/version/cmd.go
=> add version sub-command to immuclient interractive mode

cmd/immuadmin/command/init.go, cmd/immutest/command/init.go, pkg/client/options.go
=> feat: add auth support to immutest CLI

cmd/immuadmin/command/backup.go, cmd/immutest/command/init.go
=> add backup user message and new line after the last immutest user message

cmd/immuadmin/command/service/helper_windows.go
=> fix: windows build

.github/workflows/push.yml
Actions:
add windows as run step
add build (make all) as run step
=> chore: githubactions add windows and build step

pkg/auth/tokenkeys.go
=> fix: race condition in token eviction

pkg/fs/copy.go, pkg/fs/copy_test.go
=> Copy File Operations

.travis.yml
=> fix: fix travis build sleep time

cmd/immuadmin/command/login.go, cmd/immuadmin/command/user.go, cmd/immuadmin/command/user_test.go, cmd/immuclient/cli/currentstatus_test.go, cmd/immuclient/immuc/currentstatus_test.go
Signed-off-by: gjergji <gjergjiramku@gmail.com>
=> immuadmin user sub-commands and tests

cmd/cmdtest/stdout_collector.go, cmd/immuadmin/command/backup.go, cmd/immuadmin/command/backup_test.go, cmd/immuadmin/command/commandline.go, cmd/immuadmin/command/commandline_test.go, cmd/immuadmin/command/init.go, cmd/version/cmd_test.go, pkg/client/clienttest/immuclient_mock.go
Signed-off-by: Valentin Padurean <912518+padurean@users.noreply.github.com>
=> test: enhance immuadmin backup command coverage

cmd/immuadmin/command/backup.go, cmd/immuadmin/command/backup_test.go, cmd/immuadmin/command/commandline.go, cmd/immuadmin/command/init.go, pkg/immuos/filepath.go, pkg/immuos/filepath_test.go, pkg/immuos/os.go, pkg/immuos/os_test.go
Signed-off-by: Valentin Padurean <912518+padurean@users.noreply.github.com>
=> add os and filepath abstraction and use it in immuadmin backup command

cmd/immuadmin/command/backup.go, cmd/immuadmin/command/backup_test.go, pkg/fs/copy.go, pkg/fs/copy_test.go, pkg/fs/tar.go, pkg/fs/tar_test.go, pkg/fs/zip.go, pkg/fs/zip_test.go, pkg/immuos/filepath.go, pkg/immuos/filepath_test.go
Signed-off-by: Valentin Padurean <912518+padurean@users.noreply.github.com>
=> increase coverage above 90% for fs package

pkg/api/schema/item_test.go, pkg/api/schema/patterns_test.go
=> pattern item tests

cmd/immuclient/audit/init.go, cmd/immuclient/audit/init_test.go
=>  add audit init tests

README.md
=> doc: uniform and align career badge

README.md
=> doc: fix covaralls badge link

cmd/immuadmin/immuadmin.go, cmd/immudb/immudb.go
=> chore(cmd): restore error handling in main method

cmd/immuadmin/command/service/constants/freebsd.dist.go, cmd/immuadmin/command/service/constants/linux.dist.go, pkg/service/sservice_freebsd.go, pkg/service/sservice_unix.go
=> fix(pkg/service): restore correct config path

cmd/immuadmin/command/user.go, pkg/server/server.go, pkg/server/server_test.go
Signed-off-by: gjergji <gjergjiramku@gmail.com>
=> choose defaultdb on user create if not in multiple db mode

pkg/server/database_test.go, pkg/server/server_test.go
=> test(pkg/server): fix z-related test cases

README.md
=> Add link to release v0.7.0 and fix previous release links

pkg/client/token_service.go
=> fix(pkg/client): token service manages old token format

cmd/helper/config.go, cmd/helper/config_test.go, cmd/immuadmin/command/backup_test.go, cmd/immuadmin/command/commandline_test.go, cmd/immuclient/command/commandline_test.go, cmd/immudb/command/cmd.go, cmd/immudb/command/commandline_test.go, cmd/immugw/command/cmd.go, cmd/immugw/command/commandline_test.go
=> chore(cmd): remove error suppression in config loader

pkg/client/client.go, pkg/client/client_test.go, pkg/client/types.go
=> fix(pkg/client): setBatch creates structured values

pkg/client/client.go, pkg/client/client_test.go, pkg/server/server.go
=> Fix(pkg/server):Remove tokens for a user after password change 

pkg/server/server.go, pkg/signer/ecdsa.go
=> chore(pkg/server): log signer initialization in immudb start

pkg/api/schema/kvlist.go, pkg/api/schema/kvlist_test.go, pkg/store/store.go
=> chore(pkg): add kvlist validator

README.md, build/RELEASING.md
=> doc: 0.8.0 release documentation integrations

cmd/immuclient/audit/auditagent.go, cmd/immuclient/audit/auditor.go, pkg/client/auditor/auditor.go, pkg/client/auditor/auditor_test.go, pkg/client/client.go, pkg/client/client_test.go, pkg/client/rootservice/immudb_root_provider.go, pkg/client/rootservice/immudb_uuid_provider.go, pkg/client/rootservice/immudb_uuid_provider_test.go, pkg/client/rootservice/root_provider.go, pkg/client/rootservice/root_service.go, pkg/client/rootservice/root_service_test.go, pkg/client/rootservice/uuid_provider.go, pkg/client/types.go
=> refactor(pkg/client): decoupled immuclient from rootService

pkg/server/types.go
=> test(pkg/server): add a vanilla grpc server used inside tests

pkg/client/auditor/auditor.go, pkg/client/client.go, pkg/client/timestamp/default.go, pkg/client/timestamp/timestamp_test.go, pkg/client/timestamp_service_test.go, pkg/store/item.go, pkg/store/safe.go, pkg/store/scan.go, pkg/store/store.go, pkg/store/treestore.go, tools/nimmu/nimmu.go
=> chore: export uwrap and wrap value method to be used in nimmu

go.mod, pkg/auth/clientinterceptors_test.go, pkg/auth/tokens.go, pkg/client/clienttest/immuServiceClient_mock.go, pkg/server/server.go
=> fix(pkg): handle expired token error

pkg/auth/permissions.go
=> chore(pkg/auth): fix get batch permissions

README.md, cmd/immuclient/command/cmd.go, cmd/immuclient/command/cmd_test.go, cmd/immuclient/command/init.go, cmd/immuclient/command/init_test.go, cmd/immuclient/command/references_test.go, cmd/immuclient/command/root.go, cmd/immuclient/immuclient.go, cmd/immudb/command/init.go, cmd/immudb/command/root.go, pkg/client/client.go, pkg/client/options.go, pkg/server/options.go, pkg/server/server.go
=> feat: configurable max incomming msg size

cmd/immuclient/immuc/login.go, cmd/immuclient/immuc/login_test.go, pkg/server/uuid_test.go, tools/migration/migration_v0.8.go
Just a bunch of nitpicky typo fixes.
=> Fix various typos

cmd/sservice/sservice_unix.go
=> test(pkg/sservice): use delayed task for sequential actions

README.md, cmd/immudb/command/root.go
=> chore: fix typo in cmd help

cmd/immuclient/audit/auditor.go, cmd/immuclient/command/init.go, pkg/client/auditor/auditor.go, pkg/client/auditor/auditor_test.go
=> chore(server): enhance namings related audit report notification

tools/stress_tool/stress_tool.go
=> stress tool utility

pkg/store/store.go, pkg/store/store_test.go, pkg/store/treestore.go
=> fix(pkg/store): fixes issue #532

README.md
immudb is listed on awesome-go!
=> feat: Add awesome-go badge

pkg/store/errors.go, pkg/store/item.go, pkg/store/reference.go, pkg/store/reference_test.go, pkg/store/safe.go, pkg/store/safe_test.go, pkg/store/store.go
=> refactor(pkg/store): get resolve reference only by key

embedded/store/immustore.go, embedded/store/immustore_test.go, embedded/store/verification_test.go, embedded/tools/stress_tool.go
=> feat(embedded/store): add Alh method to get last committed tx ID and alh

pkg/database/all_ops.go, pkg/database/all_ops_test.go, pkg/database/database.go, pkg/database/reference.go, pkg/database/sorted_set.go
=> test(pkg/database): re-enable unit testing and add input validations

pkg/database/all_ops_test.go
=> test(pkg/database): re-enabled execAll with references

pkg/client/cache/file_cache_test.go, pkg/client/cache/history_file_cache.go, pkg/client/cache/history_file_cache_test.go, pkg/client/client.go, pkg/client/client_test.go
=> test(pkg/client): restore unit tests

cmd/immuadmin/command/stats.go, cmd/immuadmin/command/stats/metrics.go
=> Fix immuadmin stats

pkg/server/corruption_checker.go, pkg/server/corruption_checker_test.go, pkg/server/server.go, pkg/server/types.go
=> temporary remove proactive corruption checker

cmd/immudb/command/service/service_test.go, cmd/immudb/command/service/servicetest/daemon.go, cmd/immudb/command/service/servicetest/sservice.go
=> test(cmd/immudb/command/service): inncrease code coverage

pkg/client/client_test.go, pkg/server/batch.go, pkg/server/corruption_checker.go, pkg/server/corruption_checker_test.go, pkg/server/options_test.go, pkg/server/pid_test.go, pkg/server/server.go, pkg/server/server_test.go
=> re-enable server unit testing

pkg/client/client_test.go
=> test(pkg/client): add delay to ensure entries get indexed

embedded/store/immustore.go, embedded/store/immustore_test.go
=> test(embedded/store): unit testing for concurrency and hash tree re-sync

embedded/store/reader.go, embedded/store/reader_test.go, embedded/tbtree/reader.go, embedded/tbtree/snapshot.go
=> test(embedded): unit testing store reader

pkg/database/reference_test.go
=> test(pkg/database): set SinceTx value to ensure data is indexed

pkg/server/metrics_funcs.go, pkg/server/metrics_funcs_test.go, pkg/server/server.go
=> improve coverage for server metrics functions

cmd/immuadmin/command/stats/controller.go, cmd/immuadmin/command/stats/metrics.go, cmd/immuadmin/command/stats/show.go, cmd/immuadmin/command/stats/show_test.go, cmd/immuadmin/command/stats/statstest/statsResponse.go, cmd/immuadmin/command/stats/ui.go, pkg/server/metrics.go, pkg/server/metrics_funcs.go, pkg/server/metrics_funcs_test.go, pkg/server/metrics_test.go, pkg/server/server.go, pkg/server/server_test.go
- show default database name
- use last TX ID for number of entries
- show default db dir size
=> Stats fixes

pkg/client/client_test.go, pkg/server/server_test.go
=> test(pkg/server): db reloading

cmd/sservice/sservice_freebsd.go, cmd/sservice/sservice_unix.go, cmd/sservice/sservice_windows.go, pkg/immuos/user.go
=> fix(cmd/sservice): fix services management and add permissions guard

cmd/sservice/sservice_unix.go, cmd/sservice/sservice_unix_test.go, embedded/store/options.go
=> chore(embedded/store/options.go): increase DefaultMaxKeyLen

pkg/client/client.go, pkg/client/client_test.go
=> feat(pkg/client): add verifiedGetSince

pkg/client/client_test.go
=> test(pkg/client): ensure indexing is done before scanning

embedded/tbtree/tbtree.go
=> fix(embedded/tbtree): fix key history ordering

embedded/store/immustore.go, embedded/store/immustore_test.go, embedded/tools/stress_tool.go, pkg/database/database.go
=> fix(embedded/store): fix indexing sync

embedded/store/immustore.go, pkg/database/database.go
=> fix(embedded/store): continued indexing

embedded/store/immustore.go, pkg/client/client.go
=> fix(pkg/api/schema): strip prefix from returned keys in txById

pkg/client/auditor/auditor.go, pkg/client/auditor/auditor_test.go
=> fix(pkg/client/auditor): hide auditor password in logs

test/txscan/txscan.go
Added a tool for testing TxScan API
=> Added tool for TxScan testing

pkg/server/server.go, pkg/server/server_test.go
=> fix(pkg/server): use latest snapshot when listing users

pkg/client/client.go, pkg/client/streams.go, pkg/client/streams_zscan_and_history_integration_test.go, pkg/client/streams_zscan_and_history_test.go, pkg/server/servertest/server_mock.go, pkg/server/streams.go, pkg/stream/factory.go, pkg/stream/types.go, pkg/stream/zStreamer.go, pkg/stream/zparser.go, pkg/stream/zreceiver.go, pkg/stream/zsender.go
=> Add StreamZScan and StreamHistory

embedded/store/options.go
=> chore(embedded/store): set max file size to 2Gb

README.md, cmd/immuclient/command/misc.go
Fixes #653 
Signed-off-by: Duncan Mac-Vicar P <duncan@codenotary.com>
=> doc: Fix misleading usage of help as argument

cmd/helper/terminal.go
Proposed fix for https://github.com/codenotary/immudb/issues/657
```
echo -n "immudb" |  ./immuclient login immudb
Password:
inappropriate ioctl for device
```
This handles the case stdin is not a terminal:
```
echo -n immudb | ./immuclient login immudb
Successfully logged in.
```
=> fix: password reader 'inappropriate ioctl for device' from stdin

embedded/store/immustore.go
=> chore(embedded/store): remove duplicated logging

embedded/tbtree/reader_test.go, embedded/tbtree/snapshot.go
Automatically set seekKey based on prefixKey when it's not set.
When scan is descending, seekKey is padded to cover all keys with specified prefix. Thus removing the need to pad it at application side.
=> feat(embedded/tbtree): prefix-based seekKey calculation

BUILD.md, README.md
README.md is now much shorter and has a clear user story.
Yet to be done:
Fix #672
=> Refactor README.md

pkg/client/client.go, pkg/client/client_test.go
=> Call server logout even if local token file could not be deleted

cmd/immudb/command/init.go, cmd/immudb/command/root.go, configs/immudb.toml, pkg/auth/tokenkeys_test.go, pkg/auth/tokens.go, pkg/auth/tokens_test.go, pkg/server/options.go, pkg/server/server.go
=> feat: add token expiration time flag

pkg/client/clienttest/immuclient_mock_test.go
=> test(pkg/client/clienttest): fix client test mock

pkg/server/streams.go
=> fix(pkg/server): complete error handling

embedded/sql/catalog_test.go, embedded/sql/engine_test.go, embedded/sql/parser.go, embedded/sql/parser_test.go
=> sql: case insensitive identifiers

embedded/sql/catalog.go, embedded/sql/engine.go, embedded/sql/engine_test.go, embedded/sql/parser_test.go, embedded/sql/sql_grammar.y, embedded/sql/sql_parser.go, embedded/sql/stmt.go
This PR incorporates support for `NOT NULL` column constraint.
e.g. `CREATE TABLE myTable (id INTEGER, title VARCHAR, active BOOLEAN NOT NULL, PRIMARY KEY id)`
=> Feat SQL: `NOT NULL` constraint

embedded/store/immustore.go, embedded/store/indexer.go, pkg/database/all_ops_test.go
=> fix(embedded/store): fix indexing data race

embedded/tbtree/tbtree_test.go
=> test(embedded/tbtree): fix validation regarding number of key updates

embedded/sql/engine.go, embedded/sql/engine_test.go, embedded/sql/joint_row_reader.go, embedded/sql/row_reader.go, embedded/sql/stmt.go, pkg/database/database.go
=> chore(embedded/sql): safer support for selected database

pkg/auth/permissions.go
=> chore(pkg/auth): add SQL-related permissions

.github/workflows/pull.yml
Creating this PR to trigger new actions workflow
=> Testing action

embedded/tbtree/snapshot_test.go, pkg/client/sql_test.go, pkg/database/sql.go
=> fix(pkg/database): unwrap parameter before calling sqlexec

pkg/client/sql.go, pkg/client/sql_test.go
=> chore(pkg/client): auto convert numeric values to uint64

Makefile
**This is to dismis XGO and authomated multi arch/services binaries generation**
In additions:
**Added 2 new architectures:**
linux/arm64
freebsd/amd64
**Removed:**
.PHONY: nimmu
.PHONY: bm
.PHONY: bm/function
.PHONY: bm/rpc
.PHONY: bench
.PHONY: tools/comparison/mongodb
.PHONY: tools/comparison/scylladb
.PHONY: build/xgo
.PHONY: build/makensis
=> chore: improved make dist script

pkg/api/schema/row_value_test.go, pkg/pgsql/server/pgsql_integration_test.go, pkg/pgsql/server/ssl_handshake_test.go
=> coverage increased for sql related packages

pkg/database/sql_test.go, pkg/server/sql_test.go
=> unit testing sql-related functionality

embedded/sql/engine.go, embedded/sql/engine_test.go, embedded/sql/grouped_row_reader.go, embedded/sql/grouped_row_reader_test.go, embedded/sql/joint_row_reader.go, embedded/sql/joint_row_reader_test.go
=> unit testing embedded/sql

CONTRIBUTING.md, README.md
Update outdated information (key-value store only, version numbers)
=> chore: README/doc updates

cmd/immuclient/immuc/getcommands.go
Fixes #711 
I don't think we should do something about the case `-0`.
Reference: https://github.com/spf13/cobra/issues/124
=> fix(cmd/immuclient): improve immuclient tx error message

embedded/store/immustore.go
This PR reduces to one fsync call for all the values within a transaction.
This is achieved by explicitly calling Sync once all entries are written.
Note: This change increase throughput when synced mode is enabled.
=> chore(embedded/store): sync values once all entries are written

embedded/sql/parser.go, embedded/sql/parser_test.go
=> fix(embedded/sql): interprete binary prefix if followed by a quote

Makefile
This PR simplifies build process by automatically downloading latest webconsole if not present at build time
Thanks @SimoneLazzaris for your collaboration
=> automated download of webconsole if not present when building

embedded/tools/stress_tool_sql/stress_tool_sql.go, tools/testing/stress_tool_sql.go
This is a rebased containing the updates to the tools used for stress testing on the SQL engine.
=> Merge sql stress tools

cmd/immuclient/command/cmd.go, cmd/immuclient/command/currentstatus.go, cmd/immuclient/command/getcommands.go, cmd/immuclient/command/login.go, cmd/immuclient/command/misc.go, cmd/immuclient/command/references.go, cmd/immuclient/command/scanners.go, cmd/immuclient/command/setcommands.go, cmd/immuclient/command/sql.go, cmd/immuclient/command/tamperproofing.go, cmd/immuclient/immuc/login.go, cmd/immuclient/immuc/login_test.go, cmd/immuclient/immuc/misc.go, cmd/immuclient/immuc/scanners.go, cmd/immuclient/immuc/setcommands.go, cmd/immuclient/immuc/sql.go
=> remove additional blank line from immuclient output

cmd/immuclient/command/misc.go
=> cmd/immuclient: fix panic in immuclient cli mode

pkg/server/user.go
=> fix(pkg/server): lock userdata map read

pkg/server/remote_storage_test.go, pkg/server/server.go, pkg/server/types.go
=> fix(s3): Use remote storage for new databases

embedded/sql/engine.go, embedded/sql/engine_test.go
=> fix(sql/engine): Harden DecodeValue

pkg/api/schema/sql.go, pkg/api/schema/sql_test.go, pkg/client/sql_test.go
=> test(sql): Increase SQL code coverage

embedded/store/immustore.go, embedded/store/immustore_test.go
=> test(embedded/store): Increase immustore test coverage

pkg/client/auditor/auditor.go, pkg/client/auditor/auditor_test.go
=> fix(pkg/client/auditor): fix and enhance state signature verification

embedded/sql/engine_test.go, embedded/sql/proj_row_reader.go
This PR fixes table aliasing when selectors are not explicitly specified i.e. `SELECT * FROM mytable AS t`
As collateral effect, this fix seems to be fixing the column ordering. Issue mentioned here #894
=> fix table aliasing with implicit selectors

embedded/sql/engine_test.go, embedded/sql/stmt.go, embedded/store/immustore.go
This PR includes a minor fix when validating constraints at kv store level and a sql insert optimization when using auto-incremental primary keys.
=> sql insert optimization

embedded/ahtree/ahtree.go, embedded/multierr/multierr.go, embedded/multierr/multierr_test.go, embedded/store/immustore.go, embedded/store/immustore_test.go, embedded/tbtree/tbtree.go
=> multi error enhacements

pkg/client/options.go, pkg/stdlib/errors.go, pkg/stdlib/sql.go, pkg/stdlib/sql_test.go
=> chore(pkg/stdLib): implementing golang standard sql interfaces

embedded/sql/joint_row_reader.go
=> fix(embedded/sql): return error when joint table doest not exist

cmd/immuadmin/command/database.go, pkg/database/database.go, pkg/server/remote_storage.go
=> chore: remove wip warning for fully implemented features

embedded/sql/catalog.go, embedded/sql/engine_test.go
=> chore(embedded/sql): disable TIMESTAMP data-type

Dockerfile.alma
Added a Dockerfile for building immudb on an almalinux based container, for those who prefers a redhat-ish approach
=> feat: Dockerfile for almalinux based image

embedded/sql/distinct_row_reader.go, embedded/sql/limit_row_reader.go, embedded/sql/limit_row_reader_test.go, embedded/sql/proj_row_reader.go, embedded/sql/stmt.go
=> chore(embedded/sql): limit row reader

embedded/sql/engine_test.go, embedded/sql/stmt.go
=> fix(embedded/sql): correct max key length validation

embedded/sql/engine_test.go, embedded/sql/parser.go, embedded/sql/sql_grammar.y, embedded/sql/sql_parser.go, embedded/sql/stmt.go
This PR introduces logical deletion at SQL layer.
```sql
DELETE FROM mytable WHERE name = 'John'
-- optional `USE INDEX` can be specified
DELETE FROM mytable WHERE name = 'John' USE INDEX ON name
-- optional `LIMIT` can be set
DELETE FROM mytable WHERE name = 'John' USE INDEX ON name LIMIT 1
```
=> sql delete from statement

embedded/sql/engine.go, embedded/sql/engine_test.go, embedded/sql/parser.go, embedded/sql/sql_grammar.y, embedded/sql/sql_parser.go, embedded/sql/stmt.go
This PR introduces support for partial row updates
```sql
UPDATE mytable SET name = 'my_new_name', age = age+1 WHERE name = 'my_name'
-- optional `INDEX ON` to instruct the index to use during table scan
UPDATE mytable SET name = 'my_new_name' WHERE name = 'my_name' USE INDEX ON name
-- optjonal `LIMIT` can be set
UPDATE mytable SET name = 'my_new_name' WHERE name = 'my_name' USE INDEX ON name LIMIT 1
```
=> Feat sql update stmt

README.md, helm/.gitignore, helm/.helmignore, helm/Chart.yaml, helm/Makefile
added readme instructions 
added a Makefile in helm directory to build the helm package
=> Readme updates for helm

pkg/client/heartbeater/heartbeater.go, pkg/server/keep_alive_session_interceptor.go, pkg/server/sessions/manager.go, tools/long_running/stress_tool_worker_pool.go, tools/testing/stress_tool_sql.go
New version of stress tools that uses sessions and transactions.
In addition there is an important fix on keepo alive session interceptor.
=> stress tool adv

pkg/client/clienttest/immuServiceClient_mock.go, pkg/client/session.go, pkg/client/session_test.go, pkg/integration/stream_test.go
=> test(pkg/client): increase session test coverage

pkg/integration/session_test.go, pkg/integration/transaction_test.go
=> chore(pkg/integration): remove useless compilation tag on tests

cmd/immuadmin/command/commandline.go
=> chore(cmd/immuadmin/command): add super user login hint

pkg/server/options.go
=> chore(pkg/server): deprecate GetAuth and WithAuth

embedded/sql/engine_test.go, embedded/sql/stmt.go
=> fix(sql): Do not panic on error during delete

pkg/stdlib/connection.go, pkg/stdlib/connector.go, pkg/stdlib/driver.go, pkg/stdlib/rows.go, pkg/stdlib/rows_test.go, pkg/stdlib/sql_test.go, pkg/stdlib/tx.go, pkg/stdlib/tx_test.go, pkg/stdlib/uri.go, pkg/stdlib/uri_test.go
this PR expose tx on standard lib
=> feat(pkg/stdlib): expose tx on std lib

cmd/immuclient/command/commandline.go, cmd/immuclient/immuc/setcommands.go
=> fix interactive use database

cmd/immuclient/immuc/login.go
=> chore(cmd/immuclient): return actual login error

CODE_OF_CONDUCT.md
- added CODE_OF_CONDUCT.md file
=> chore: create code of conduct markdown file

pkg/server/server.go, pkg/server/server_test.go
=> validate if db is not replica then other replication attrs are unset

pkg/client/cache/file_cache.go, pkg/client/cache/file_cache_test.go
=> fix(client/file_cache): Fix storing immudb state in file cache

embedded/store/immustore.go
When waiting for a vLog lock, don't check for close flag
that could introduce deadlock with store's mutex.
=> fix(embedded/immustore): Avoid deadlock when acquire vLog lock

build/RELEASING.md
=> chore(build): improve release instructions

Makefile, build/RELEASING.md
=> chore(makefile): fix cas sign instructions

embedded/store/immustore.go
=> sync aht when syncing the store

embedded/cache/lru_cache.go, embedded/tbtree/tbtree.go
This is a very simple implementation, to be changed in https://github.com/codenotary/immudb/issues/1081
=> chore(stats): Add btree cache prometheus stats

embedded/tbtree/tbtree.go
=> use binary search during key lookups

.dockerignore, Dockerfile, embedded/ahtree/ahtree.go, embedded/appendable/multiapp/multi_app.go, embedded/appendable/singleapp/single_app.go, embedded/cache/lru_cache.go, embedded/cache/lru_cache_test.go, embedded/store/immustore.go, embedded/store/immustore_test.go, embedded/store/indexer.go, embedded/store/options.go, embedded/store/options_test.go, embedded/store/tx.go, embedded/store/tx_reader.go, embedded/tbtree/metrics.go, embedded/tbtree/options.go, embedded/tbtree/snapshot.go, embedded/tbtree/tbtree.go, embedded/tbtree/tbtree_test.go, pkg/server/options.go
Includes different split method and independent flush&sync while flushing, improved logging during compaction
Note: includes latest added indexing metrics
=> Indexing optimizations

embedded/tbtree/tbtree.go
Attempt to load snapshot only when there is at least one commit log entry.
Compaction will create an entry in commit log after successful completion. Otherwise attempt to read older snapshot is done. Starting a fresh index if none of the existent snapshots are valid.
=> improve snapshot loading and discarding

embedded/tbtree/tbtree.go
=> chore(embedded/tbtree): Use KV entries count for sync threshold

embedded/tbtree/tbtree.go
=> chore(embedded/tbtree): explicit error validation before loading

.github/workflows/push.yml
=> upgrade vcn version

embedded/store/indexer.go, embedded/store/indexer_test.go, embedded/tbtree/options.go, embedded/tbtree/options_test.go, embedded/tbtree/tbtree_test.go, pkg/database/database_test.go
=> chore(embedded/tbtree): positive compaction threshold

embedded/tbtree/tbtree.go, pkg/database/all_ops_test.go, pkg/database/database_test.go
=> chore(embedded/tbtree): validate compaction target path

pkg/server/server.go
=> fix(pkg/server): Use buffered channel for catching OS signals

embedded/store/immustore.go, embedded/store/options.go, embedded/store/options_test.go, pkg/server/db_options.go, pkg/server/server_test.go
=> fix(pkg/client): Prevent updates with incorrect database settings

embedded/store/options.go
=> chore(embedded/store/options): Simplify validation tests

pkg/server/server.go
Signed-off-by: Benjamin Gentil <benjamin@gentil.io>
=> fix(pkg/server): typo in log message

embedded/store/immustore.go, embedded/store/immustore_test.go
Early precondition checks must be done at the most recently
committed transaction when the write was issued.
Before this change, it was possible to run the precondition
check against the most recently indexed transaction which could
result with erroneous precondition failures.
=> fix(embedded/store): Fix early precondition checks

pkg/server/server.go
=> chore(pkg/server): tolerate failed user-created db loading

embedded/sql/engine.go, embedded/sql/row_reader.go, embedded/store/immustore.go, embedded/store/immustore_test.go, embedded/store/indexer.go, embedded/store/key_reader.go, embedded/store/ongoing_tx.go, embedded/store/ongoing_tx_test.go, embedded/store/preconditions.go, embedded/store/tx.go, embedded/store/tx_test.go, pkg/api/schema/database_protoconv.go, pkg/database/scan.go, pkg/database/sorted_set.go
=> chore(embedded/store): use store layer for constraint validations

pkg/client/errors/errors.go, pkg/client/errors/meta.go, pkg/errors/map.go, pkg/errors/meta.go, pkg/server/errors.go, pkg/server/errors_test.go
=> fix(pkg/errors): Correct GRPC error mapping for precondition failure

pkg/database/database.go, pkg/database/database_test.go
=> fix(pkg/database): return key not found when resolving a deleted entry

build/RELEASING.md
* Mention which tasks are necessary for RC release
* Remove manual cas notarization steps - those are done
automatically in Github Actions
=> chore(build/RELEASING.md): Update releasing docs

pkg/server/db_operations.go
=> fix(pkg/server): include db name in flush index result

tools/testing/stress_tool_test_kv/README.md, tools/testing/stress_tool_test_kv/stress_tool_kv.go
=> chore(tools/testing): Add stress tool

pkg/auth/clientinterceptors.go, pkg/auth/clientinterceptors_test.go, pkg/client/client.go
=> fix(pkg/auth): Do not send duplicated authorization header

.github/workflows/pull.yml, .github/workflows/push.yml, .github/workflows/stress.yml
* go Use 1.17 compiler to build binaries
* check if binaries can be built with go 1.13
* build binaries with `make dist` and notarize all binaries
compiled that way
=> chore(github): Update github workflow on master / version push

README.md
=> chore(README.md): Switch to github badge

build/RELEASING.md
=> chore(build): Update the RELEASING.md documentation

embedded/sql/engine_test.go, embedded/sql/values_row_reader.go, embedded/sql/values_row_reader_test.go
=> fix(embedded/sql): selector resolution using valuesRowReader

embedded/sql/engine_test.go, embedded/sql/stmt.go
=> return invalid value when using aggregated col selector in temporal queries

README.md
=> fix(README): Update readme to show examples for 1.3.0 version

build/RELEASING.md
=> chore(build): Update RELEASING.md file

pkg/client/session.go, pkg/client/session_test.go, pkg/integration/session_test.go
=> fix: ensure connection is closed and session can be re-established

.github/workflows/pull.yml, pkg/integration/fuzzing/grpc_fuzz_test.go
* build with all supported go versions
* unit tests only for the main go version
* smoke tests for all compilede versions
* update default version to 1.17
* add mac osx build/test
=> chore(github): Update push action - go 1.18 compatibility

cmd/immuadmin/command/hot_backup.go
=> fix(cmd/immuadmin): use StreamChunkSize as max chunk size

embedded/appendable/remoteapp/remote_app_test.go, embedded/remotestorage/memory/memory.go, embedded/remotestorage/memory/memory_test.go, embedded/remotestorage/remote_storage.go, embedded/remotestorage/s3/s3.go, embedded/remotestorage/s3/s3_test.go, pkg/server/metrics.go, pkg/server/remote_storage.go, pkg/server/remote_storage_test.go
=> chore(remotestorage): Add prometheus metrics for remote storage kind

embedded/store/immustore.go
=> fix(embedded/store): ensure tx is released upon error

Makefile
=> chore(Makefile): Update webconsole to 1.0.16

cmd/immuadmin/command/stats.go, cmd/immuadmin/command/stats_test.go, cmd/immuclient/cli/register.go, cmd/immuclient/cli/server_info.go, cmd/immuclient/command/cmd_test.go, cmd/immuclient/command/commandline.go, cmd/immuclient/command/server_info.go, cmd/immuclient/command/server_info_test.go, cmd/immuclient/immuc/init.go, cmd/immuclient/immuc/misc.go, cmd/immuclient/immuc/misc_test.go, cmd/immuclient/immuc/print.go, cmd/immuclient/immuc/server_info.go, cmd/immuclient/immuc/server_info_test.go, pkg/api/schema/docs.md, pkg/api/schema/schema.proto, pkg/api/schema/schema.swagger.json, pkg/api/schema/schema_grpc.pb.go, pkg/client/client.go
Closes https://github.com/codenotary/immudb/issues/1281.
Related: https://github.com/codenotary/immudb/pull/1266.
=> Add `info` (`rpc ServerInfo`) to immuclient

embedded/ahtree/ahtree_test.go
Convert Edge Cases test to test suite and run each test independently.
=> test(embedded/ahtree): Update tests

embedded/ahtree/ahtree.go, embedded/ahtree/ahtree_test.go, embedded/ahtree/options.go, embedded/ahtree/options_test.go
=> chore(embedded/ahtree): improve validations and error handling

embedded/appendable/singleapp/single_app_test.go
=> appendable: unit test read/write using file and inmem buffering

.dockerignore, .github/workflows/pull.yml, .github/workflows/push.yml, Makefile, build/fips/Dockerfile, build/fips/Dockerfile.build, build/fips/Dockerfile.immuadmin, build/fips/Dockerfile.immuclient, build/fips/check-fips.sh, cmd/immuadmin/fips/fips.go, cmd/immuclient/command/cmd.go, cmd/immuclient/fips/fips.go, cmd/immudb/command/cmd.go, cmd/immudb/fips/fips.go, cmd/version/cmd.go, go.mod, pkg/client/auditor/monitoring_server.go, pkg/server/metrics.go
- add Dockerfile for fips build
- add cmd/immudb/fips folder to enable fips check and immudb build
- add Makefile changes for generating FIPS build with cgo enabled
=> chore(Dockerfile): add fips build changes

pkg/api/schema/docs.md, pkg/api/schema/schema.pb.go, pkg/api/schema/schema.proto, pkg/api/schema/schema.swagger.json, pkg/client/client.go, pkg/client/errors.go, pkg/client/get_options.go, pkg/client/mtls_options.go, pkg/client/options.go, pkg/client/session.go, pkg/client/session_id_injector_interceptor.go, pkg/client/sql.go, pkg/client/stream_replication.go, pkg/client/streams.go, pkg/client/timestamp_service.go, pkg/client/token_interceptor.go, pkg/client/transaction.go, pkg/client/types.go, pkg/server/server.go, pkg/server/user.go
=> doc(pkg/client): Add inline godoc comments to pkg/client

pkg/server/server.go
Addresses #1385 
- add logs for replicator if it is not required/configured
=> chore(pkg/server): add logs for replicator

pkg/database/database.go, pkg/database/replica_test.go, pkg/integration/replication/suite.go, pkg/integration/replication/synchronous_replication_test.go, pkg/server/db_dummy_closed.go, pkg/server/server.go
=> [sync replication] further integration test scenarios

embedded/store/immustore.go, pkg/database/database.go, pkg/database/replica_test.go, pkg/integration/replication/docker.go, pkg/integration/replication/server.go, pkg/integration/replication/suite.go, pkg/integration/replication/synchronous_replication_test.go, pkg/replication/replicator.go, pkg/server/db_dummy_closed.go, pkg/server/db_dummy_closed_test.go, pkg/server/server.go, pkg/server/stream_replication.go
=> fix(pkg/replication): solve issues when follower diverged from master

.github/workflows/push.yml
=> fix(build): Do not publish official non-dev images on RC tags

.github/workflows/performance.yml, .github/workflows/push.yml, .github/workflows/stress.yml
- Add missing line breaks to Mattermost message
- Extract Go version from environment variable to pass it to reusable workflow
=> feat(ci): fix message and input

embedded/appendable/appendable.go, embedded/appendable/fileutils/fileutils.go, embedded/appendable/fileutils/fileutils_unix.go, embedded/appendable/fileutils/fileutils_windows.go, embedded/appendable/multiapp/multi_app.go, embedded/appendable/multiapp/multi_app_test.go, embedded/appendable/remoteapp/remote_app.go, embedded/appendable/singleapp/single_app.go
=> fix(embedded/appendable): fsync parent directory

docs/security/PROOFS.md
=> docs(security): Add documentation for client-side proofs

embedded/sql/engine_test.go, embedded/store/immustore_test.go, pkg/database/replica_test.go, pkg/server/transaction_test.go
=> test(embedded/sql): unit testing type inference with casting

pkg/client/heartbeater/heartbeater.go, pkg/client/session.go
=> fix(pkg/client): ensure ticker is properly stopped

.github/workflows/performance.yml, .github/workflows/stress.yml
Change Mattermost channel.
Add duration and immudb version.
Signed-off-by: Marco Sanchotene <marco@codenotary.com>
=> feat(ci): change notification

embedded/appendable/multiapp/multi_app.go
=> fix(embedded/appendable): proper closing of non-required chunks

.github/workflows/performance.yml, .github/workflows/stress.yml
Add seconds to duration for performance tests.
Add duration to stress tests.
Signed-off-by: Marco Sanchotene <marco@codenotary.com>
=> chore(ci): improve notifications

.github/workflows/pull.yml, .github/workflows/push.yml
=> use gosec action

embedded/sql/engine_test.go, embedded/sql/stmt.go
=> fix(embedded/sql): multi-row conflict handling

embedded/store/immustore.go, embedded/store/key_reader.go
=> fix(embedded/store): integrity checks covering empty values

.github/workflows/performance.yml, test/performance-test-suite/cmd/perf-test/main.go, test/performance-test-suite/pkg/runner/influxdb_client.go
- Add flags to send GitHub runner and immudb version along with tests results to InfluxDB
=> chore(test/perf): add runner to results for influxdb

pkg/integration/replication/synchronous_replication_test.go
=> test(pkg/integration): Add test case to reveal hang during DB update

test/document_storage_tests/documents_tests/actions/create_collections.go, test/document_storage_tests/documents_tests/actions/login.go, test/document_storage_tests/documents_tests/create_collections_test.go, test/document_storage_tests/documents_tests/delete_collections_test.go
extract common actions into separate functions
=> test(delete-collection): add tests to delete collections

embedded/sql/engine.go, embedded/sql/engine_test.go, embedded/sql/sql_tx.go, embedded/store/immustore.go, embedded/store/ongoing_tx.go, pkg/database/sql.go, pkg/replication/options.go, pkg/replication/options_test.go, pkg/replication/replicator.go, pkg/server/options.go, test/release_perf_test/Dockerfile, test/release_perf_test/Dockerfile-141, test/release_perf_test/quickie.sh, test/release_perf_test/startup.sh
this PR should provide a fix for #1670
=> Fix sync rep

cmd/immuadmin/command/user_test.go, cmd/immuclient/audit/auditor_test.go, cmd/immuclient/immuc/currentstatus_errors_test.go, cmd/immuclient/immuc/getcommands_errors_test.go, cmd/immuclient/immuc/login_errors_test.go, cmd/immuclient/immuc/misc_errors_test.go, cmd/immuclient/immuc/references_errors_test.go, cmd/immuclient/immuc/scanners_errors_test.go, cmd/immuclient/immuc/setcommands_errors_test.go, cmd/immutest/command/cmd_test.go, embedded/appendable/multiapp/multi_app_test.go, embedded/appendable/remoteapp/remote_app_test.go, embedded/appendable/remoteapp/remote_storage_reader_test.go, embedded/appendable/singleapp/single_app_test.go, embedded/cache/lru_cache_test.go, embedded/remotestorage/memory/memory_test.go, embedded/sql/aggregated_values_test.go, embedded/sql/cond_row_reader_test.go, embedded/sql/distinct_row_reader_test.go, embedded/sql/engine_test.go, embedded/sql/grouped_row_reader_test.go, embedded/sql/joint_row_reader_test.go, embedded/sql/limit_row_reader_test.go, embedded/sql/offset_row_reader_test.go, pkg/database/all_ops_test.go, pkg/database/replica_test.go, pkg/errors/errors_test.go, pkg/immuos/os_test.go, pkg/server/server_test.go
Convert error checking into more readable form
Mostly generated by search+replace (with regex)
=> chore(tests): Tests cleanup

Makefile
This calls subsequent make commands, which is a downside
=> fix(Makefile): remove webconsole tag from immuclient/immuadmin builds

embedded/sql/parser_test.go, embedded/sql/sql_grammar.y, embedded/sql/sql_parser.go
```sql
create table mytable(id integer, title varchar(50), payload blob(256), primary key id)
```
=> sql: support parenthesis as datatype constraint delimiter

pkg/integration/session_test.go, pkg/server/session.go
Close #1721 
Please @jeroiraz check this one out!
=> fix: lower databasename in OpenSession

.github/workflows/pull.yml, embedded/cache/lru_cache.go
- validate input params before obtaining mutex lock
- replace sync.Mutex with sync.RWMutex
=> LRUCache optimizations

BUILD.md, Dockerfile, build/Dockerfile, build/Dockerfile.alma, build/Dockerfile.full, build/Dockerfile.immuadmin, build/Dockerfile.immuclient, build/Dockerfile.rndpass, build/e2e/Dockerfile, build/fips/Dockerfile, build/fips/Dockerfile.immuadmin, build/fips/Dockerfile.immuclient
This PR will provide a solution to https://github.com/codenotary/immudb/issues/1781
Once this is merged, i will open another PR to fix the github actions to use it.
=> chore: Add support to ARM64

.github/workflows/push.yml
=> .github/workflows/push.yml

pkg/database/database.go, pkg/database/database_test.go, pkg/database/scan.go, pkg/database/scan_test.go, pkg/database/sorted_set.go, pkg/database/sql.go, pkg/database/sql_test.go
=> Fix/issue 1331/limit off by one

embedded/appendable/remoteapp/remote_app.go, embedded/remotestorage/s3/s3.go
This PR is the same as the one discussed on #2002 . Only difference is that I used one signed commit.
=> Fix AWS Signature V4 using IAM role

embedded/document/engine.go, embedded/sql/aggregated_values.go, embedded/sql/engine.go, embedded/sql/engine_test.go, embedded/sql/functions.go, embedded/sql/grouped_row_reader.go, embedded/sql/grouped_row_reader_test.go, embedded/sql/json_type.go, embedded/sql/num_operator.go, embedded/sql/num_operator_test.go, embedded/sql/parser.go, embedded/sql/parser_test.go, embedded/sql/proj_row_reader.go, embedded/sql/sql_grammar.y, embedded/sql/sql_parser.go, embedded/sql/stmt.go, embedded/sql/stmt_test.go, embedded/sql/type_conversion.go, embedded/sql/values_row_reader.go, embedded/sql/values_row_reader_test.go, embedded/store/options.go
- Allow selecting generic expressions;
- Refactor FnCall implementation;
- Add support for INSERT INTO SELECT statements;
- Add more core builtin functions;
=> chore(embedded/sql): SQL layer improvements
