codenotary/immudb

cmd/cmd.go

fix(cmd): get and safeget error for non-existing key

---

cmd/immuclient/immuclient.go
pkg/client/batch_request.go
pkg/client/timestamp/default.go
pkg/client/timestamp/ntp.go
pkg/client/timestamp/tsgenerator.go
pkg/client/timestamp_service.go
pkg/store/safe_test.go

There is a long list of improvements to make the code more readable and standard according to Go idioms. This pull-request is the first contribution to the project and so I want to keep it simple to familiarize myself with the contribution guidelines and branch management. Depending on how the discussion goes and if these changes are merged, I will continue sending more pull-requests of trivial things like ineffectual variable assignments, misaligned struct types, redundant statements, etc. Later when I am more familiar with the code I will contribute new features.
find . -type f -name "*.go" -exec gofmt -s -w {} \;

fix: code format for multiple files to comply with Go coding standards

---

Makefile

Using the latest git tag proved to be unreliable: the sort order was wrong in `git tag --sort=-version:refname | head -n 1` => the first in the list was RC-2, which is incorrect. We could've sorted by `-creatordate` and that would've worked, but if tags which represent something other than a version would be used in the future, this could still cause problems.
So i decided to just use the manually entered version instead since (it was already present and used in the Makefile, hence it already needs to be manually bumped).

build: use hardcoded, manually-bumped version instead of git tag

---

pkg/client/client_test.go

Hi @mmeloni & @Gjergj 
I am not sure how good this idea is, so i am asking for your feedback through this PR:
**what do you think about using Badger in-memory (only) for tests which are not meant to test the store itself?**
As an example, i've modified the client tests to use this approach.

use badger in memory for client tests

---

pkg/server/server.go

fix: skip loading databases from disk when in memory is requested

---

pkg/server/corruption_checker.go

Corruption checker is a non-stop validation and as such, it cannot rely on recursive invocations.

improvement(pkg/server): avoid recursion on corruption checker

---

cmd/helper/config.go
cmd/helper/config_test.go
cmd/immuadmin/command/backup_test.go
cmd/immuadmin/command/commandline_test.go
cmd/immuclient/audit/auditor_test.go
cmd/immuclient/command/commandline_test.go
cmd/immudb/command/commandline_test.go
cmd/immugw/command/commandline_test.go

Without this change, while _**immuclient**_ and _**immuadmin**_ still worked as expected, _**immudb**_ and _**immugw**_ `version` and `mangen` commands (and possibly other ones too) are throwing the following error:
```
./immugw version
Error: flag accessed but not defined: config
Usage:
immugw version [flags]
Flags:
-h, --help   help for version
flag accessed but not defined: config
```

Fix immudb and immugw version and mangen commands errors

---

embedded/tools/stress_tool.go

fix(embedded/tools): catch ErrNoMoreEntries when iterating over txs

---

embedded/tbtree/tbtree.go

fix(embedded/tbtree): sync GetTs to prevent data races

---

pkg/server/options.go

feat: increase default store max value length to 32MB

---

pkg/server/options.go

chore(pkg/server): max recv msg size is set to 32M

---

embedded/tbtree/reader.go
embedded/tbtree/reader_test.go

Terminate reader (return NoMoreEntries) if prefix won't be satisfied any more:
- Ascending mode:  if current entry has a prefix greater than the specified one;
- Descending mode: if current entry has a prefix lower than the specified one;

chore(embedded/tbtree): terminate reader if prefix won't match any more

---

embedded/appendable/multiapp/multi_app_test.go
embedded/appendable/singleapp/single_app_test.go
pkg/client/cache/history_file_cache_test.go
pkg/client/cache/inmemory_cache_test.go
pkg/client/streams.go
pkg/streamutils/files.go
pkg/streamutils/files_test.go

* Add test for streamutils (100%)
* Streams: Remove some duplicate ErrNotConnected handling, which prevents tests from reaching error handling
* The Verified methods stay as before, as the Verification happens before the connection checks
* A few coverage improvements for pkg/client/cache (file creation)
* A few coverage improvements for embedded/appendable (file creation)
Total: +0.2% :muscle:

Misc coverage improvements

---

cmd/immuclient/cli/cli_test.go
cmd/immuclient/immuclienttest/helper.go
pkg/client/client.go
pkg/client/client_test.go
pkg/client/errors.go
pkg/client/illegal_state_handler_interceptor.go
pkg/server/error_mapper_interceptor.go
pkg/server/errors.go
pkg/server/server.go
pkg/server/servertest/server.go
pkg/server/servertest/server_mock.go
pkg/server/types.go

This PR aims to improve UX on client SDK when immudb returns an illegal state error message.
Inside an error handler interceptor when illegal state is found the local state is checked and compared with the server one.
If the server one is older (like after a restore) the information is explained to the client

improve SDK UX on handling immudb illegal state

---

embedded/store/immustore.go
pkg/database/all_ops_test.go
pkg/database/scan.go
pkg/database/scan_test.go
pkg/database/sorted_set.go
pkg/database/sorted_set_test.go

This PR changes default parameters when scanning keys by prefix and sorted-sets, default parameters will make use of a fully up-to-date snapshot.
If older snapshots can be used (or reused) `sinceTx=TxID` can be specified as a requirement for the index state

Scans running over fully up-to-date snapshots as default behaviour

---

README.md

Unnecessary quotation mark and incorrect placement of mascot due to less content

fix: readme typo and mascot placement

---

embedded/store/immustore.go
embedded/store/immustore_test.go

When the max number of concurrent transactions is reached (default 10) value logs are not released.
This PR solves this locking issues by ensuring channels get closed and locks properly released.

Fix concurrency issue when max concurrent tx limit is reached

---

embedded/store/immustore.go
embedded/store/key_reader.go
embedded/store/key_reader_test.go
embedded/tbtree/reader.go
embedded/tbtree/reader_test.go
embedded/tbtree/tbtree.go
pkg/database/scan.go
pkg/database/sorted_set.go

This PR includes a new reader operation `ReadAsBefore(txID)`
This functionality is analogous to traditional key-prefix scanning but ignoring any change occurred since the specified transaction.
Note: This functionality leverages history log on indexing and it does not involve any additional snapshot handling.

Read as before

---

.github/workflows/stress.yml

This PR adds a workflow to run the stress tools on the same table as our README benchmarks.
It would add an additional layer of safety to detect problems in the store.

chore: github workflow to run stress_tool

---

Makefile
tools.go

This PR makes the code generation tools work via the normal dependency system, so that there is no need to grab them from a .zip file.
The tools.go approach is a common pattern for code generation. A build constraint prevents the code to be compiled-in, but makes the go.mod system install it into the go workspace bin/ like any other module.
Please test in your system with `make build/codegen` in case I missed something.

Handle code generation tools via modules

---

pkg/api/schema/schema.proto

This PR adds the missing annotations to expose the SQL methods that are used to generate the gateway
As master also changed the API prefix for those (when @mmeloni updated immugw), I changed those as well so that it will be - easier to merge later.
The idea is to add the REST gw and its options in master, but have ready the SQL end-points in here.

Add http annotations to SQL rpc methods

---

pkg/client/cache/cache.go
pkg/client/cache/file_cache.go
pkg/client/cache/file_cache_test.go
pkg/client/cache/history_file_cache.go
pkg/client/cache/inmemory_cache.go
pkg/client/cache/inmemory_cache_test.go
pkg/client/state/state_service.go

In order to make possible that client sdk can be run by multiple processes on same state file it was introduced a file lock solution.
We detected unexpected beahviour on windows (lock fail) and this PR replace completely the previous implementation.
Instead of a mutex (that make not possible to write on a locked file) we use lockfile primitive. 
lockfile.Openfile is used to acquire the lock, and close to release and the locked file object pointer is keep in memory during operations.

fix(pkg/client/cache): fix lock file cache issue on windows

---

cmd/immuadmin/command/stats/controller.go
cmd/immuadmin/command/stats/metrics.go
cmd/immuadmin/command/stats/show.go
pkg/server/metrics.go
pkg/server/metrics_funcs.go
pkg/server/metrics_funcs_test.go
pkg/server/metrics_test.go
pkg/server/server.go

closes #730 
Examples from the response of the `/metrics` endpoint:
---
```bash
immudb_db_size_bytes{db="cnlcdata"} 61044
immudb_db_size_bytes{db="cnlcinternalledger"} 20600
immudb_db_size_bytes{db="cnlcsyslogledger"} 2156
immudb_db_size_bytes{db="defaultdb"} 20612
immudb_db_size_bytes{db="lcledgeronekkgeln"} 107992
immudb_db_size_bytes{db="systemdb"} 11158
```
⚠️ The db sizes are **NOT** the actual size that is occupied on the disk. I tried to do it, initially, but it only worked on Linux (using `Fstat` from golang.org/x/sys package). I already spent to much time trying to find out how to do it in a cross-platform way, so i resorted to the same approach that is on `master` which uses `os.FileInfo.Size()`.
---
```bash
immudb_number_of_stored_entries{db="cnlcdata"} 34 …
```

Enhance metrics for DB size and number of entries to support multiple databases and add CORS to metrics endpoints

---

.github/workflows/pull.yml
embedded/tools/stress_tool_sql.go

This is an initial stress tool following the same pattern as `stress_tool.go` but using the embedded SQL engine.
Caveats:
* It fails if the database exists
* It generates serial IDs without persisting the last, therefore 2 consecutive runs would fail with duplicate IDs (perhaps a flag in the future indicating starting ID would help)

feat(embedded/tools): initial SQL stress tool

---

cmd/immudb/command/tls_config.go
pkg/pgsql/server/ssl_handshake.go
pkg/server/webserver.go
pkg/server/webserver_test.go

Before pgsql branch merge, tlsConfig was nil if no TLS configured. This is not longer the case.
We don't make assumptions about the resulting tlsConfig object anymore. We *do* only start a TLS server if tlsConfig is non-nil and has certificates, but we only test the resulting server can accept the right type of connection.

fix: tlsConfig semantics changed when no TLS configured

---

pkg/server/server.go

This PR is a request to add version when starting up the server. It is the less intrusive way that I thought of, without moving parts of cmd/version around.
```
_                               _ _
(_)                             | | |
_ _ __ ___  _ __ ___  _   _  __| | |__
| | '_ ` _ \| '_ ` _ \| | | |/ _` | '_ \
| | | | | | | | | | | | |_| | (_| | |_) |
|_|_| |_| |_|_| |_| |_|\__,_|\__,_|_.__/
immudb 0.9.2
Commit  : 36738cd16d8d020c99ef121e57791fc401c4e65e
Built by: xxxxxxxx@codenotary.com
Built at: Wed, 19 May 2021 18:50:51 CEST
================ Config ================
Data dir         : /dev/shm/immu4
Address          : 0.0.0.0:3322
Metrics address  : 0.0.0.0:9497/metrics
Config file      : configs/immudb.toml
Max recv msg size: 33554432
Auth enabled     : true
Dev mode         : false …
```

feat: display version at startup

---

webconsole/.gitignore
webconsole/webconsole.go

The way statik works is by generating a module. This module is not present until go generate is run.
This is not a problem as the files are guarded by build tags, but go mod vendor and go mod tidy run with all build tags enabled, which result in a module referenced but not present.
This is an alternative fix to https://github.com/codenotary/immudb/pull/794 suggested by @jeroiraz 
Instead of a dummy `statik` module, we generate the statik data instead of the `webconsole` module itself, which is always present.
In addition to the suggestion, I have also added a flag to *statik* to guard the file with the `webconsole` build tag and added `dist` and `statik.go` to `.gitignore`.
This is a workaround. We should eventually use go embed present in Go 1.16.

fix: go mod tidy/vendor with statik module

---

pkg/server/server.go
pkg/server/uuid.go
pkg/server/uuid_test.go

the file used to reside in default DB dir. Because the file contains cross-database information, it should not be in default db dir.
Fixes #799

move server UUID file to data dir

---

embedded/tbtree/tbtree_test.go

Small sync fix inside btree unit testing. Ensure insertions have finished before closing.

test(embedded/tbtree): fix sync inside unit testing

---

cmd/immuclient/cli/cli.go

This PR just makes it so if you hit CTRL+D on immuclient it will exit instead of ignoring it, see issue [819](https://github.com/codenotary/immudb/issues/819)

Changed EOF handling for immuclient

---

embedded/tbtree/tbtree_test.go

This PR contains a small fix on a random key insertion unit testing.
The issue was that in case of a key update, the timestamp was compared with the first timestamp instead of the latest one.

test(embedded/tbtree): compare against latest key update

---

embedded/store/immustore.go

This PR applies global `synced` configuration to indexing data structure in order to prevent inconsistencies during unexpected/forced terminations.
While some performance degradation may be expected, it shouldn't be much noticeable to final applications given indexing data is eventually flushed to disk. Furthermore, depending on the use case, eventual indexing feature can be used per transaction basis by setting attribute `NoWait=true`.
This approach may be useful until a more elaborated solution is implemented i.e. #823

Apply synced settings to indexing data

---

pkg/database/database.go

Database registration may be needed when opening a database created with an older version of immudb (older than v1.0.0)
This PR handles the above described situation by registering the database in the catalog as part of the database opening procedure.

Auto-registration when database is not present in the catalog

---

cmd/immuclient/cli/register.go

This PR changes the `exec` and `query` commands to variable ones.
That way those commands can accept arbitrary number of arguments without issuing a warning in the interactive mode.
Closes  #803

fix(cmd/immuclient): remove warnings on sql commands in interactive mode

---

embedded/appendable/multiapp/multi_app.go
embedded/appendable/multiapp/multi_app_test.go

Ensure to use the current appender if the `ReadAt` function reads the data stored inside that appender.

fix: consistent reads of recently written data

---

pkg/stream/execall_receiver.go
pkg/stream/execall_sender.go
pkg/stream/kvparser.go
pkg/stream/kvreceiver.go
pkg/stream/receiver.go
pkg/stream/sender.go
pkg/stream/ventryreceiver.go
pkg/stream/zreceiver.go

Fix naming on stream api object in order to clarify the purpose of message sender and receiver parameters

chore(pkg/stream): fix namings on stream api objects

---

embedded/sql/engine_test.go
embedded/sql/parser.go
embedded/sql/parser_test.go
embedded/sql/sql_grammar.y
embedded/sql/sql_parser.go
embedded/sql/stmt.go

This PR introduces initial(*) support for positional parameters in sql statements
e.g. `SELECT * FROM mytable WHERE id > $1 OR ($2 AND active)`
```
params, err = engine.InferParameters("SELECT * FROM mytable WHERE id > $1 OR ($2 AND active)")
require.NoError(t, err)
require.Len(t, params, 2)
require.Equal(t, IntegerType, params["param1"])
require.Equal(t, BooleanType, params["param2"])
```
Note: Validation of using either named (positional or non-positional) or unnamed parameters is currently done while parsing.
Although the underlying datatype carries such information (pos attribute) in case semantic validations are additionally added.
(*): semantic validations regarding parameters are not included e.g. `SELECT * from mytable WHERE id = $2` will be valid besides parameter `$1` is not …

Sql positional parameters

---

embedded/ahtree/ahtree.go
embedded/store/immustore.go
embedded/store/immustore_test.go
embedded/tbtree/tbtree.go
embedded/tbtree/tbtree_test.go

Index compaction was not handling data syncing as expected. IO errors might not have been detected leading to inconsistent snapshots, requiring index re-generation.

Fix index compaction data syncing

---

pkg/pgsql/server/options.go
pkg/pgsql/server/server.go
pkg/server/server.go

I've found a weird behavior of immudb, specifically the psql port.
If I ask immudb to bind to a specific IP address (i.e. `--address 127.0.0.2`)  I find only 3 out of 4 port bind are actually made to that interface:
```
$ ss -plnt|grep immudb
LISTEN 0      0          127.0.0.2:9497       0.0.0.0:*    users:(("immudb",pid=458586,fd=26))   
LISTEN 0      0          127.0.0.2:3322       0.0.0.0:*    users:(("immudb",pid=458586,fd=24))   
LISTEN 0      0          127.0.0.2:8080       0.0.0.0:*    users:(("immudb",pid=458586,fd=27))   
LISTEN 0      0                  *:5432             *:*    users:(("immudb",pid=458586,fd=25))   
```
Port 5432 is always binding to every interface.
That prevents me to (easily) launch to instance on the same machine, binding the first one on (say) `127.0.0.2` …

fix: bind psql port to the same IP address as grpc interface

---

embedded/ahtree/ahtree.go
embedded/ahtree/ahtree_test.go
embedded/store/immustore.go
embedded/store/immustore_test.go
embedded/store/indexer.go
embedded/store/indexer_test.go
embedded/tbtree/snapshot_test.go
embedded/tbtree/tbtree.go
embedded/tbtree/tbtree_test.go
pkg/client/stream_replication_test.go

This PR includes:
- Fix an issue in btree flushing step to make it crash tolerant. Current solution is based on `SetOffset` operation as originally designed. Which may evolve to support garbage with a full or pseudo-full appendable implementation.
- Auto truncation of commit logs based on fixed commit entry sizes. Originally, an error was retuned if an inconsistency was produced in commit logs. This point was discussed during a team meeting and mentioned as part of a more broad discussion #858.
- Btree initialization following a similar approach to MultiAppendable initialization. Btree compaction creates a full dump of the tree into new folders, previously the folders to use were fixed i.e. `nodes` and `commit` but since this change, the folders are dynamically chosen from the most recent …

automated snapshot recovery

---

embedded/sql/engine.go
embedded/sql/engine_test.go
embedded/sql/grouped_row_reader_test.go
embedded/sql/joint_row_reader_test.go
embedded/tbtree/tbtree.go
embedded/watchers/watchers_test.go
pkg/database/database.go
pkg/database/database_test.go
pkg/database/sql.go
pkg/server/options.go

SQL Functionality requires the catalog to be loaded. Currently, this implies indexing be up to date.
In cases were a complete index regeneration was required, initialization was blocking. Depending on the amount of data, not being able to periodically call compaction may require an excessive amount of disk space.
This PR places SQL initialization into the background, thus operations which don't require the indexing to be up to date can be normally executed.

non-blocking sql initialization

---

embedded/store/immustore_test.go
embedded/store/indexer.go

Indexing go-routine was't using the reserved concurrency slot allocated for that purpose. As consequence of this, it was competing for resources as a normal transaction. Slowing down indexing tasks and potentially blocking if max concurrency limit was reached with synchronous commits.

fix(embedded/store): use reserved concurrency slot for indexing

---

pkg/client/auditor/auditor.go
pkg/server/sever_current_state_test.go
pkg/signer/ecdsa.go
pkg/signer/ecdsa_test.go

This PR addresses the changes requested by @byo & @mmeloni in the previous PR which was already merged - see these comments for details:
@mmeloni Please not that i actually did something a bit different than what you suggested (to avoid exposing `ecdsa.PublicKey` in generic `Signer` interface): i just called in the auditor code the existing `UnmarshalKey` function from signer package (which i enhanced a bit by returning an error if the key bytes are not a valid key).

Improve signature verification during audit

---

embedded/sql/catalog.go
pkg/database/sql.go

In order to correctly identifying autoincremental column(s) in table, I've added the `AUTO INCREMENT` column to the `describe` call.
It is a boolean field, default to false.
```sql
immuclient>exec CREATE TABLE demo (id INTEGER AUTO_INCREMENT, description VARCHAR, PRIMARY KEY id)
Updated rows: 0 
immuclient>describe demo
+---------------+-----------+----------+---------------+----------------+
|    COLUMN     |   TYPE    | NULLABLE |     INDEX     | AUTO INCREMENT |
+---------------+-----------+----------+---------------+----------------+
| "id"          | "INTEGER" | false    | "PRIMARY KEY" | true           |
| "description" | "VARCHAR" | true     | "NO"          | false          |
+---------------+-----------+----------+---------------+----------------+
```﻿

Adding AUTO_INCREMENT column to describe table

---

embedded/sql/cond_row_reader.go
embedded/sql/cond_row_reader_test.go
embedded/sql/engine.go
embedded/sql/engine_test.go
embedded/sql/grouped_row_reader.go
embedded/sql/grouped_row_reader_test.go
embedded/sql/joint_row_reader.go
embedded/sql/joint_row_reader_test.go
embedded/sql/proj_row_reader.go
embedded/sql/row_reader.go
embedded/sql/stmt.go

This PR enforces all rows of the same group are consecutive so to get up most one entry per group.
As a consequence of this enforcement, grouping is restricted to the indexed column the results are ordered by.
```sql
CREATE TABLE t1(id INTEGER AUTO_INCREMENT, val1 INTEGER, PRIMARY KEY id)
CREATE INDEX ON t1(val1)
SELECT COUNT() as c FROM t1 GROUP BY val1 ORDER BY val1
```

fix(embedded/sql): enforce ordering by grouping column

---

.github/workflows/pull.yml
BUILD.md
Dockerfile
Makefile
build/RELEASING.md

Makefile now contains an information what webconsole version
is the best match for the current immudb code. That version is
selected when building with `make WEBSONCOLE=default ...`.
Alternatively one can select the latest released version of
webconsole with `make WEBCONSOLE=latest ...` or use a specific
version with `make WEBCONSOLE=<version> ...`.

chore(Makefile): More explicit webconsole version

---

Dockerfile.rndpass

In order to random generate a password, the environmental variable `IMMUDB_ADMIN_PASSWORD` has to be unset, so I removed the default value in the (specific) Dockerfile

Fix: env variable for immudb password must not be set 

---

embedded/sql/engine_test.go
embedded/sql/parser.go
embedded/sql/parser_test.go
embedded/sql/sql_parser.go

The PR was modified to provide sql standard escaping with single quotes
```sql
create table mytable(title varchar[50], primary key title)
insert into mytable(title) values ('my escaped ''string''')
select * from mytable
+---------------------------+
| (DEFAULTDB MYTABLE TITLE) |
+---------------------------+
| "my escaped 'string'"     |
+---------------------------+
```
While we can support both escaping methods, the previous one was not correctly covering all the cases.

chore(embedded/sql): support for escaped strings

---

embedded/store/immustore_test.go
embedded/tbtree/snapshot.go
embedded/tbtree/tbtree.go

This PR fixes tx read conflicts by ensuring all entries in the snapshot get the same logical insertion time i.e. txID

fix(embedded/tbtree): set fixed snapshot ts

---

embedded/sql/stmt.go
embedded/store/immustore.go
embedded/store/immustore_test.go
embedded/store/key_reader.go
embedded/store/kv_metadata.go
embedded/store/kv_metadata_test.go
embedded/store/ongoing_tx.go
embedded/store/tx.go
embedded/tools/stress_tool/stress_tool.go
pkg/api/schema/database_protoconv.go
pkg/database/database.go

The initial implementation for data expiration was preventing access to values of expired entries but with a significative lost in performance.
This PR aims to solve the performance issue while still ensuring data of expired entries is not reachable.
KVMetadata struct contains a private readonly attribute used to allow or forbid changes. When reading committed data this attribute is automatically set to true, making impossible to dynamically change it using exposed apis.

Optimization safe readvalue

---

embedded/store/immustore.go
embedded/store/immustore_test.go
embedded/store/tx.go

This PR introduces readonly private attribute on tx entries. This value can only be set internally when loading tx data from storage.
This attribute is then checked when reading a value associated to a key at a specific tx.

readonly tx entries to ensure no runtime modification

---

embedded/store/immustore.go
pkg/replication/replicator.go

This PR just adds a delay in case of any error while replicating the incoming transaction.
More advanced handling may be implemented in the future but this change is just to prevent polluting the logs with the same error message too often

chore(pkg/replication): delay replication after failure

---

embedded/sql/engine.go
embedded/sql/timestamp.go
embedded/sql/timestamp_test.go
pkg/api/schema/row_value.go
pkg/api/schema/sql.go
pkg/api/schema/sql_test.go
pkg/client/sql.go
pkg/database/sql.go
pkg/stdlib/rows.go
pkg/stdlib/rows_test.go

This PR fixes and issues with timestamp columns in sql tables. Although timestamps are stored in microseconds, the sql client sdk converted time.Time argument values into nanoseconds ( pkg/client/sql.go , line 332 ). Afterwards the nanosecond value was converted back into a time.Time value before writing it to the database. But in this instance it was interpreted as microseconds ( pkg/api/schema/row_value.go, line 198 ). Hence a totally wrong timestamp is stored. Similarly the client sdk retrieved timestamps in nanoseconds when queried from the database.
To fix this issue and make timestamp handling more consistent, the PR adjusts all locations setting a value for SQLValue_Ts.Ts to ensure it is always assigned a microsecond value. As the conversion formula was copied to multiple …

bugfix: Transfer timestamp in microseconds to fix timestamp column values.

---

Dockerfile

Without CA certificates, immudb is unable to connect
to official S3 servers.

fix(Dockerfile): Add ca-certificates.crt file to immudb image

---

pkg/api/schema/ops.go
pkg/api/schema/ops_test.go
pkg/database/all_ops.go
pkg/database/all_ops_test.go
pkg/database/reference.go
pkg/database/sorted_set.go

ExecAll operation provides the capability to atomically insert key-value pairs, references and sorted set entries. Even the possibility to bind references to the entries inserted into the ongoing transaction.
Due to the presence of references, the indexing must be up to date, degrading performance when execAll request is self-contained i.e. references are only created to entries written in the same request.
This PR leverages NoWait parameter to avoid waiting for the indexing to be up to date (faster processing time) at the expense of restricting references to be made to entries specified in the ongoing request.
As a side effect, not only a reference of references may be created in the database but also a reference entry can be switched to a plain key-value entry or the other way around. …

restricted and optimized ExecAll

---

embedded/sql/parser.go
embedded/sql/parser_test.go

This PR adds support for using `<>` in a not equal comparison in SQL queries. The current syntax `!=` for the operator is not affected by the change and can still be used.
The ANSI SQL standard defines `<>` as symbol for a not equal operator, but not `!=` (see e.g. https://en.wikipedia.org/wiki/Where_(SQL) ). Nevertheless most database engines (e.g. mysql, postgres)  support both `<>` and `!=` and  both can be used interchangeably.  To improve compatibility with automatic SQL statement generators, it would be advantageous to also support both. For example gorm creates SQL statements with `<>` in where clauses.
A Unit test for parsing `<>` as well as `!=` in a where clause is included in the PR.

add <> as alternative to != in sql queries

---

embedded/tbtree/consistency_error_test.go
embedded/tbtree/snapshot.go
embedded/tbtree/tbtree.go

This PR includes ensures cache is not affected when reading nodes during compaction

no cache update during compaction reads

---

embedded/tbtree/tbtree.go

chore(embedded/tbtree): rebase non-indexed on kv syncthreshold

---

embedded/tbtree/metrics.go
embedded/tbtree/snapshot.go
embedded/tbtree/snapshot_test.go
embedded/tbtree/tbtree.go
embedded/tbtree/tbtree_test.go

* Add correct compaction metrics (previously merged with flush)
* Add label for nodes count to distinguish between inner and leaf nodes
* Add counters for number of values
* Add progress reporting during compaction

chore(metrics): Add better flush / compaction metrics for btree

---

pkg/client/client.go
pkg/client/clienttest/immuclient_mock.go

The response from `UpdateDatabaseV2` GRPC endpoint is a dedicated structure currently containing only the current settings.
The pkg/client however did return directly those settings only preventing future extensions for that response without breaking backwards compatibility.

fix(pkg/client): Use correct response for UpdateDatabaseV2

---

cmd/immuadmin/command/database.go

fix(cmd/immuadmin): simplify logging when flushing and compacting

---

Dockerfile

With an empty HOME variable, immudb fail to start on podman
with the following message:
"Error: user: Current requires cgo or $HOME set in environment"
This fails here: https://cs.opensource.google/go/go/+/master:src/os/user/lookup_stubs.go;l=58
Because `HOME="${IMMUDB_HOME}"` on line 71 is not set without a prior `ARG`
For some reason docker always sets a HOME variable so it doesn't have this issue.
Signed-off-by: Benjamin Gentil <benjamin@gentil.io>

fix(Dockerfile): Fix HOME variable for podman

---

embedded/sql/catalog.go
embedded/sql/catalog_test.go
embedded/sql/dummy_data_source_test.go
embedded/sql/dummy_row_reader_test.go
embedded/sql/engine.go
embedded/sql/engine_test.go
embedded/sql/grouped_row_reader.go
embedded/sql/joint_row_reader.go
embedded/sql/parser.go
embedded/sql/parser_test.go
embedded/sql/proj_row_reader.go
embedded/sql/row_reader.go
embedded/sql/sql_grammar.y
embedded/sql/sql_parser.go
embedded/sql/stmt.go
embedded/sql/stmt_test.go
embedded/sql/union_row_reader.go
embedded/sql/union_row_reader_test.go
embedded/tools/stress_tool_sql/stress_tool_sql.go
pkg/database/database.go
pkg/database/sql.go
pkg/database/sql_test.go
pkg/integration/transaction_test.go
pkg/server/db_dummy_closed.go
pkg/stdlib/tx_test.go

This PR introduces support for UNION operator.
All subqueries must select the same number of columns, with the same types. While names can differ, the final return will assign the naming as in the first subquery.
```sql
SELECT * FROM mytable WHERE id < 10 UNION SELECT * FROM mytable WHERE id > 10
SELECT MAX(age) FROM mytable1 UNION ALL SELECT MIN(age) FROM mytable2
```

sql union operator

---

embedded/sql/engine_test.go
embedded/sql/stmt.go

fixes the situation that could let auto_increment columns be increased multiple times per row when nullable columns were defined in the table and no value was specified at insertion time

fix(embedded/sql): increase auto_increment pk once per row

---

embedded/sql/engine.go
embedded/sql/engine_test.go
embedded/sql/stmt.go
embedded/tools/stress_tool_sql/stress_tool_sql.go
pkg/database/database.go
pkg/database/database_test.go
pkg/database/sql.go
pkg/integration/session_test.go
pkg/pgsql/server/query_machine.go
pkg/server/db_dummy_closed.go
pkg/server/multidb_handler.go

TODO: extract multidb handler from the sql engine
Note:
Database creation  (`CREATE DATABASE`) and selection  (`USE DATABASE`) statements are non-transactional in both, embedded and with external multidb handler (e.g. when using the server for processing these statements).
Therefore, this two statements are not allowed inside a `BEGIN TRANSACTION`/`COMMIT`|`ROLLBACK` block

non-transactional statements handling

---

.github/workflows/pull.yml

It turns out that sonarcloud requries coverage file generated
during coverage analysis. This change brings back sonarcloud
analysis to the Coverage job where such file is present.

fix(github): Run sonarcloud code analysis after cove coverate

---

pkg/database/all_ops_test.go
pkg/database/database.go
pkg/database/database_test.go
pkg/database/scan.go
pkg/database/scan_test.go
pkg/database/sorted_set.go
pkg/database/sorted_set_test.go
pkg/database/sql.go
pkg/database/sql_test.go
pkg/server/db_dummy_closed.go
pkg/server/db_dummy_closed_test.go

fix(pkg/database): avoid silent returns when the scan limit is reached

---

.github/workflows/pull.yml
.github/workflows/push.yml
Makefile
embedded/remotestorage/remote_storage.go
embedded/remotestorage/s3/s3.go
embedded/remotestorage/s3/s3_test.go
embedded/remotestorage/s3/s3_with_minio_test.go
pkg/server/remote_storage.go
pkg/server/remote_storage_test.go

In some setups (elest.io minio containers) HEAD requets fail
when talking to the container. Workaround the HEAD request
by using object lists instead.
Also correctly handle URL-encoded object names and paths when
getting the list, fixes #1207.

fix(embedded/remotestorage/s3): S3 compatibility fixes

---

embedded/sql/aggregated_values.go
embedded/sql/cond_row_reader.go
embedded/sql/engine.go
embedded/sql/engine_test.go
embedded/sql/stmt.go
embedded/sql/values_row_reader.go
embedded/store/ongoing_tx.go

This PR includes a fixed timestamp associated to ongoing transactions.
SQL `now()` function evals to the fixed transaction timestamp. Thus making `now()` an idempotent function in the scope of the same transaction.
```sql
-- column `ts` of the three inserted rows will contain the same value
INSERT INTO mytable(id, ts) VALUES (1, NOW()), (2, NOW()), (3, NOW());
-- or equivalently
BEGIN TRANSACTION;
INSERT INTO mytable(id, ts) VALUES (1, NOW());
INSERT INTO mytable(id, ts) VALUES (2, NOW()), (3, NOW());
COMMIT;
```

Tx Timestamp and SQL NOW function

---

.github/workflows/push.yml
Makefile
build/RELEASING.md
build/gen-downloads-md.sh

Changes to github actions:
* Install qemu binaries using `docker/setup-qemu-action` GH action - that will install newer qemu that does not cause issues with s390x platform
* Upgrade the way we generate file checksums - the new output does include already split and structured text making it easier to add into release notes

chore(github): Install qemu using docker/setup-qemu-action

---

helm/templates/ingress.yaml

The helm chart contains a bug within the ingress template. It uses `.Values.ingress.tls.enabled` to check if tls is enabled within the annotations settings. As the annotations section is surrounded with a `with` definition, the scope is changed within it to `.Values.ingress.annotations`. Therefore  `.Values.ingress.tls.enabled` actually looks up `.Values.ingress.annotations.Values.ingress.tls.enabled`, which does not exist.
The fix adds a `$` to actually use the global scope when checking if tls is enabled.

fix: access tls value in global scope within ingress annotations

---

.github/workflows/pull.yml
.github/workflows/push.yml
.github/workflows/stress.yml

Go 1.19 has just been released. Switch the main go compiler
version to 1.18 and start testing with 1.19.

chore: Update main go versin to 1.18

---

Dockerfile
Dockerfile.alma
Dockerfile.immuadmin
Dockerfile.immuclient
Dockerfile.rndpass

Updates go version to 1.18 in Dockerfile builds
Signed-off-by: Farhan Khan <farhan@codenotary.com>

fix(build): update go version to 1.18 in Dockerfiles

---

pkg/pgsql/server/pgsql_integration_test.go
pkg/stdlib/sql_test.go

- fixes issue with flaky tests which fail due to table already exists error
References: [1324](https://github.com/codenotary/immudb/issues/1324)

fix(getRandomTable): increase RNG range for table generation

---

pkg/client/clienttest/homedir_mock.go
pkg/client/clienttest/immuServiceClient_mock.go
pkg/client/clienttest/immuclient_mock.go
pkg/client/clienttest/immuclient_mock_test.go
pkg/client/clienttest/token_service_mock.go

These changes are required for https://github.com/codenotary/immugw to work, as it depends on mock clients from client test
- add interface assertion for immuclient
- add interface assertion for immuServiceClient
- add interface assertion for tokenservice
References: https://github.com/codenotary/immudb-issues/issues/76

fix(pkg/client/clienttest): enforce mock client to interface

---

.github/dependabot.yaml

Dependabot helps to keep all packages and dependencies up to date. This prevents from using vulnerable dependencies. It automatically creates PRs for dependency update, which we can then approve and merge.
Note, this does not automatically merge any PR. It just creates PRs for vulnerable dependencies. More on dependabot here
[Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)

chore: add dependabot config

---

pkg/integration/replication/suite.go
pkg/integration/replication/synchronous_replication_test.go

This method is a useful utility to ensure that the replica committed given transaction id. This is necessary because shortly after replica confirms the write to primary that transaction will still be in a precommitted state thus we have to wait for another sync cycle on replica to make it committed.

test(pkg/integration/replicatino): Add WaitForCommittedTx

---

pkg/integration/replication/server.go
pkg/integration/replication/suite.go

* Actively check if server instance is running instead of 1s sleep
* When setting up cluster, spawn replicas in parallel

test(pkg/integration/replication): Speedup sync replication tests

---

embedded/watchers/watchers.go
embedded/watchers/watchers_test.go
pkg/integration/replication/synchronous_replication_test.go

Invariant is broken if at the same time both the cancellation occurs and fulfilment of the condition happen.

fix(embedded/watchers): Fix invariant violation in watchers

---

pkg/client/session.go

- Original parent context comes from OpenSession which uses timeout scope of 60 seconds
- Once original context gets cancel it will force keepAlive loop to fail on each iteration
- The background context passed to keepAlive release it from parent context limitation

fix(pkg/client): replace keepAlive context from the original one to the background, avoiding parent expiration

---

cmd/immuclient/immuc/print.go

Include precommit state when querying database status to simplify master election

chore(cmd/immuclient): include precommit state when querying status

---

.github/workflows/performance.yml
.github/workflows/push.yml
.github/workflows/stress.yml

- Trigger performance and stress tests daily at midnight
- Send results to the `immudb` channel on Mattermost
Please add a secret with the Mattermost webhook as `MATTERMOST_WEBHOOK_URL` before merging this pull request.

Add scheduled daily test runs and send results to Mattermost

---

.github/workflows/performance.yml
.github/workflows/pull.yml
.github/workflows/push.yml

Replace deprecating `set-output` command with `$GITHUB_OUTPUT`.
Closes #1438.

chore(ci): migrate deprecating set-output commands

---

pkg/auth/clientinterceptors_test.go
pkg/client/homedir/homedir_test.go
pkg/client/streams_verified_integration_test.go
pkg/client/timestamp/timestamp_test.go
pkg/client/timestamp_service_test.go
pkg/logger/json_test.go
pkg/server/errors_test.go
pkg/server/metrics_test.go
pkg/server/options_test.go
pkg/server/server_test.go
pkg/server/sever_current_state_test.go
pkg/server/state_signer_test.go
pkg/server/webserver_test.go
pkg/signer/ecdsa_test.go
pkg/stream/sender_test.go

Replaced assert with require as mentioned in [this issue](https://github.com/codenotary/immudb/issues/1436).
As this is my first contribution to your project and to open source at all I'm making this pull request only in scope of `pkg/`.
I intentionally omitted replacement in `pkg/server/sessions/options_test.go` because I would argue that it's beneficial to see all errors related to configuration at once instead of only the first that is raised. I did not revert existing `require` to `assert` tho.
I'm open for suggestions, and if pull is accepted I'm happy to contribute further.

Replaced assert with require in pkg/

---

embedded/store/immustore.go
embedded/store/immustore_test.go
embedded/store/ongoing_tx.go
embedded/store/ongoing_tx_keyreader.go
embedded/store/options.go
embedded/store/options_test.go
pkg/api/schema/docs.md
pkg/api/schema/schema.pb.go
pkg/api/schema/schema.proto
pkg/api/schema/schema.swagger.json
pkg/integration/database_creation_test.go
pkg/server/db_options.go

This PR sets a configurable maximum size for the read-set used to validate transaction conflicts
Note: This PR may be reviewed after PR #1467

MVCC read-set with boundaries

---

embedded/store/immustore.go
embedded/store/ongoing_tx.go

This PR introduces support for read-only transactions.
The benefit of this type of transactions is that MVCC validations are disabled for this type of transactions. It means, read-only transactions should be faster and lighter than read-write ones.
Note: This PR may be reviewed after PR #1470

read-only transactions

---

embedded/store/immustore.go
embedded/store/indexer.go
embedded/store/ongoing_tx.go
embedded/store/ongoing_tx_options.go
embedded/tbtree/snapshot.go
embedded/tbtree/tbtree.go
embedded/tbtree/tbtree_test.go
pkg/database/database_test.go
pkg/integration/client_test.go
pkg/server/server_test.go

This PR introduces optimizations in bulk insertions by following an optimistic concurrent approach.
KV pairs to be inserted are first distributed among corresponding nodes and insertion takes place at the same time, finally the new list of nodes is built up.

tbtree optimizations

---

embedded/store/immustore.go
embedded/tbtree/consistency_error_test.go
embedded/tbtree/snapshot.go
embedded/tbtree/tbtree.go
embedded/tbtree/tbtree_test.go

This PR introduces support for multi-timed bulk insertions. Each entry may have associated its own logical timestamp.
Previously, all the entries were associated to the same timestamp i.e. root's current timestamp increased by one.
This functionality will be used to group multiple transactions for bulk insertion in the btree. However those changes will be implemented as part of a different PR.

tbtree: multi-timed bulk insertions

---

embedded/ahtree/ahtree.go
embedded/ahtree/ahtree_test.go
embedded/appendable/multiapp/multi_app.go

test(embedded/ahtree): include payload len into plog
fix(embedded/appendable): prevent moving forward when setting offset in multi-appendable
test(embedded/ahtree): unit test checking append after reopening

fix(embedded/ahtree): correct calculation of payload offset

---

embedded/appendable/remoteapp/remote_app_test.go
embedded/store/immustore_test.go
pkg/client/cache/file_cache_test.go
pkg/client/cache/history_file_cache_test.go
pkg/integration/auditor_test.go
pkg/integration/follower_replication_test.go
pkg/integration/server_recovery_test.go
pkg/pgsql/server/pgsql_integration_test.go
pkg/replication/replicator_test.go
pkg/server/db_options_test.go
pkg/server/db_runtime_test.go
pkg/server/remote_storage_test.go
pkg/server/service_test.go
pkg/server/sessions/internal/transactions/transactions_test.go
pkg/server/sever_current_state_test.go
pkg/server/sql_test.go
pkg/server/stream_replication_test.go
pkg/server/stream_test.go
pkg/server/transaction_test.go
pkg/server/types_test.go
pkg/server/user_test.go
pkg/server/webserver_test.go
pkg/streamutils/files_test.go

A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `T.TempDir` to create temporary test directory

---

pkg/client/streams.go
pkg/client/streams_integration_test.go

Signed-off-by: Axay sagathiya <axaysagathiya@gmail.com>
- Returned error when verifiedGet operation fails.
- Removed unneeded fmt.Sprintf().

Remove useless code.

---

.github/workflows/performance.yml
test/performance-test-suite/pkg/benchmarks/writetxs/benchmark.go
test/performance-test-suite/pkg/runner/benchmarks.go

This is a summary of a sample result of the changed performance tests:
```sh
Write TX/s - no replicas
TX: 18810, KV: 18810, TX/s: 1880.98, KV/S: 1880.98, CPUTime: 3.86, VMM: 2.29G, RSS: 321.01M, Writes (bytes/calls): 14.30M/88987, Reads (bytes/calls): 90.11k/190709
Write KV/s - no replicas
TX: 3438, KV: 3438000, TX/s: 341.78, KV/S: 341777.54, CPUTime: 38.33, VMM: 3.92G, RSS: 1.61G, Writes (bytes/calls): 910.06M/106995, Reads (bytes/calls): 29.41M/120928
Write TX/s - one async replica
TX: 9240, KV: 9240, TX/s: 923.91, KV/S: 923.91, CPUTime: 6.27, VMM: 5.18G, RSS: 1.83G, Writes (bytes/calls): 63.80M/136470, Reads (bytes/calls): 1.86M/285687
Write KV/s - one async replica
TX: 756, KV: 756000, TX/s: 75.60, KV/S: 75596.01, CPUTime: 12.50, VMM: 6.52G, RSS: 3.35G, Writes (bytes/calls): …
```

Extend immudb performance tests with immudb replication sync/async

---

pkg/database/scan.go
pkg/database/scan_test.go
pkg/database/sorted_set.go

eof error, which is returned when data is truncated, should not block reading scanning all keys

fix(pkg/database): skip eof error during scan

---

helm/templates/statefulset.yaml
helm/values.yaml

This PR fixes  the securityContext and podSecurityContext settings in the helm chart. 
The podSecurityContext can be specified for a pod and has e.g. the fsGroup field, whereas a securityContext can be specified in the scope of a container and contains e.g. the capabilities field. Currently these settings are mixed up in the helm chart. The podSecurityContext fields are assigned to the securityContext key in the values file and vice versa. 
Furthermore the StatefulSet definition contains two times the securityContext key for the pod sec. First time the field is set to the content if the securityContext value and the second time to the podSecurityContext  value. Correspondingly the resulting yaml is invalid. Helm is still able to install the template, but at least in my current version …

fix(helm): set securityContext & podSecurityContext in right location

---

test/performance-test-suite/pkg/runner/influxdb_client.go

With the proxy the data will be sent to the InfluxDB instance when the performance tests run on the `benchmark` runner.

chore(test/perf-tests): use proxy on benchmark runner

---

pkg/client/client.go
pkg/client/heartbeater.go
pkg/client/heartbeater/heartbeater.go
pkg/client/session.go
pkg/client/types.go
pkg/database/database_test.go
pkg/database/truncator_test.go

- PR created in top of v.1.3.2 release
- Fix Heartbeater KeepAlive context, original context has 60 seconds timeout scope, use context.Background as context base
- Add ErrorHandler callback to allow upper layers react on Heartbeater KeepAlive failure

fix heartbeater keepAlive context, add errorHandler to notify upper layers on keepAlive error

---

test/performance-test-suite/pkg/runner/influxdb_client.go

After this is merged, the data will be correctly sent to InfluxDB.

chore(test/perf-tests): remove runner check

---

embedded/sql/engine_test.go
embedded/sql/stmt.go

One way an error can be returned is when an SQL parameter in a WHERE statement is missing.
fixes #1508

fix(embedded/sql): crash when RowReader.Read() returns error

---

test/release_perf_test/.gitignore
test/release_perf_test/Dockerfile
test/release_perf_test/Dockerfile-141
test/release_perf_test/Dockerfile.tools
test/release_perf_test/README.md
test/release_perf_test/docker-compose.yaml
test/release_perf_test/doctest.sh
test/release_perf_test/runme.sh
test/release_perf_test/startup.sh

This PR adds an automated suite for running a matrix of tests, with different batch sizes, different number of concurrent client and different replication settings, for KV, SQL and Json document subsystems.
Since the branch I was working on has some issue merging (some rebasing, maybe) I've created a new branch with all significant files

Performance test matrix

---

embedded/appendable/fileutils/fileutils_unix_nonlinux.go

freebsd binaries were correctly build during the release but it may depend on the go version
this PR aims to fix #1716

fix(embedded/appendable): explicit freebsd build clauses

---

test/e2e/requirements.txt

There are 1 security vulnerabilities found in certifi 2022.12.7
- [CVE-2022-23491](https://www.oscs1024.com/hd/CVE-2022-23491)
Upgrade certifi from 2022.12.7 to 2022.12.07 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade certifi to 2022.12.07

---

embedded/tbtree/tbtree.go
embedded/tbtree/tbtree_test.go

This PR addresses an issue related to the insertion timestamp (ts) of key-value pairs within the tbtree. The problem is that the insertion ts for key-values was can be equal to the current root ts, which can cause unexpected behavior and inconsistencies in the data records.
I have added a test case to validate the correctness of this fix and to prevent any potential regressions in the future.

fix: insertion ts for key-values should not be equal to the current root ts

---

embedded/sql/type_conversion.go
pkg/client/client.go
pkg/client/clienttest/immuclient_mock.go
pkg/client/clienttest/immuclient_mock_test.go

Used if you need access to the underlying data used for verification.

feature: add (back) VerifiableGet function

---

pkg/integration/database_creation_test.go
pkg/server/server.go
pkg/server/server_test.go

This should solve the #1770. This change introduces the support of an underscore in the database name.  
- `pkg/server/server.go` - adds an additional case to checking the character validation.
- `pkg/integration/database_creation_test.go#159` - a new test for db creation with a name containing the `_`
- `pkg/server/server_test.go#1892` - unit test which tests the underscore in the isValidDBName
Signed-off-by: Martin Jirku <martin@jirku.sk>

feat(pkg/server): add support of underscore in db name

---

tools/rndpass/startup.sh

Fix https://github.com/codenotary/immudb/issues/1868: user can just set
/etc/sysconfig/immudb with desired env variables.

fix: source /etc/sysconfig/immudb on AWS EC2 startup

---

.github/workflows/push-dev.yml
.github/workflows/push.yml

The GitHub workflow push.yml was updated to use the repository owner's Docker images instead of fixed ones. 
This change allows for more flexibility and control when using Docker images, and ensures that the correct images are used based on the repository owner.
This allow forked repos to not push in the immudb organization by default

chore: set repository_owner dynamically in the push workflow.

---

.github/workflows/push.yml

Merge after #1947 
In the push.yml file, the docker images build process has been updated. 
The changes include the use of QEMU and Docker Buildx. 
Docker images for various environments like scratch, Debian version, Alma version, etc., are now built and pushed using Docker's build-push-action.
This is a partial change to ease the review process.

chore: refactor image building

---

cmd/helper/terminal.go
cmd/immuadmin/command/commandline.go
cmd/immuadmin/command/login.go
cmd/immuadmin/command/user.go
pkg/server/server.go
pkg/server/server_test.go
pkg/server/user.go

This PR is meant to relax immudb's password policy in order to match `PostgreSQL/MySQL` behavior (allow any password to be set). 
Previously, the user was required to always set a strong password either at first login or user creation time (even though the `changepassword` command allowed to set a non strong password).
A warning is still prompted to the user in the case a weak password is entered, but they can choose to ignore it.

Allow the user to force unsafe password in immuadmin

---

Dockerfile
embedded/sql/engine.go
embedded/sql/engine_test.go
embedded/sql/file_sort.go
embedded/sql/options.go
embedded/sql/options_test.go
embedded/sql/row_reader.go
embedded/sql/sort_reader.go
embedded/sql/sort_reader_test.go
embedded/sql/sql_tx.go
embedded/sql/stmt.go

This merge request is meant to support the order by clause on non indexed fields.
If the query planner determines that the output is not already sorted, then an additional sorting step is added through a new type of reader: `sortReader`.
When the client attempts to read the first row on the sort reader, all rows gets fetched from the underlying reader and collected to a buffer. When the buffer contains at least 1024 rows, sorting is performed in memory and the sorted chunk is spilled to a temporary disk file. The process continues until all the result rows have been read. 
At this point, sorted disk chunks (if any) are merged into a single bigger sorted chunk and a reader to such a file is returned to the client. If the output contains a number of rows <= 1024, then a reader to the buffer …

Allow order by on non-indexed fields

---

build/Dockerfile.immuadmin
cmd/immuadmin/command/commandline.go
pkg/client/tokenservice/file.go

Fix env in Dockerfile.immuadmin and issue in connect() function

---

pkg/client/client.go
pkg/client/streams.go

This commit fixes the complaining from `go vet` about the deferring of `time.Since`. This can cause wrong time evaluation of the elapsed time. This impact only the debug level, but still it should be addressed.
ref: https://github.com/golang/go/issues/60048
Signed-off-by: Maurizio Del Corno <druznek@gmail.com>

fix: time.Since should not be used in defer statement

---

cmd/immudb/command/init.go
embedded/sql/functions.go
embedded/store/immustore.go
embedded/store/indexer.go
embedded/store/indexer_test.go
embedded/store/options.go
embedded/store/options_test.go
embedded/tbtree/options.go
embedded/tbtree/tbtree.go
pkg/database/types.go
pkg/helpers/semaphore/semaphore.go
pkg/server/db_options.go
pkg/server/options.go
pkg/server/remote_storage.go
pkg/server/server.go
pkg/server/types.go

- implement memory aware flushing;
- share node cache across multiple indexes;
- implement write stalling;
- avoid to allocate large buffers when store.maxValueSize is too large.

chore(embedded/store): improve index flush logic

---

cmd/immudb/command/init.go
cmd/immudb/command/parse_options.go

The 'Config file:' line in immudb startup logs always showed the hardcoded default value `configs/immudb.toml` regardless of which config file was actually loaded via the `--config` flag or `IMMUDB_CONFIG` env var.
Tested on my local minikube cluster, the actual path is reflected in immudb logs on startup now.

fix: display actual config file path in startup logs

---

helm/Chart.yaml
helm/templates/configmap.yaml
helm/templates/statefulset.yaml
helm/values.yaml

- Add environment variables configuration support
- Add TOML configuration file support via ConfigMap
- Add command line arguments support
- Add S3 storage configuration capabilities
- Add secure credential management via Kubernetes secrets
- Bump chart version to 1.9.8
Resolves #2028

feat(helm): Add comprehensive configuration support for ImmuDB
